dataset: beeradvocate
field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: overall
LABEL_FIELD: label
load_col:
  inter: [user_id, item_id, overall, timestamp]
val_interval:
  overall: "[3,inf)"
unused_col:
  inter: [overall]
user_inter_num_interval: "[10,inf)"
item_inter_num_interval: "[10,inf)"
